//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerCrud.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CustomerTable
    {
        [Required(ErrorMessage ="First name is required")]
        public string Fname { get; set; }
        [Required(ErrorMessage = "Last name is required")]
        public string Lname { get; set; }
        [Required(ErrorMessage = "Age is required")]
        public Nullable<int> Age { get; set; }
        [Required(ErrorMessage = "Choose Nationality")]
        public string Nationality { get; set; }
        [Required(ErrorMessage = "Choose Country")]
        public string Country { get; set; }
        [Required(ErrorMessage = "Choose State")]
        public string State { get; set; }
        [Required(ErrorMessage = "Choose City")]
        public string City { get; set; }
        [Required(ErrorMessage = "Address is required")]
        public string Address { get; set; }
        public int Id { get; set; }
        public string CustID { get; set; }
        public Nullable<bool> Isactive { get; set; }
    }
}
